### ISSUE TITLE
Readme file needs enhancement

### ISSUE THREAD

**Issue by issavejdani** [AbolfaZlRezaEe/NMock#56]
## What's the problem or feature?

The readme file has some grammar and sentence structure issues. It also needs steps on how to use the project and setup it up for yourself.

## For the solution we want to

Fix some grammar issues and sentence structure problems that we have right now in our README.md file.

[And this is the result.](https://github.com/issavejdani/NMock/tree/doc-fix)

**Comment by AbolfaZlRezaEe** [comment]
Oh, thanks❤️. 
First of all, I edit your comment with the project style. and for reviewing it, please open a pull request to see the result. then, we can have a discussion about it.

**Comment by issavejdani** [comment]
Perfect, thank you. I will.

**Comment by AbolfaZlRezaEe** [comment]
Sorry for the delay. I reviewed the pull request and write some issues that it has. please check and write your comments.

**Comment by issavejdani** [comment]
Thank you. Resolved already. Please take a look and let me know if anything is missing.
